
name: 'Terraform Deploy to Azure'

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        env:
          ARM_CLIENT_ID: 
          ARM_SUBSCRIPTION_ID: cf59511e-1dbb-417d-ba5e-185454d163ee
          ARM_TENANT_ID: 
        run: terraform apply -auto-approve
