
name: 'Terraform Deploy to Azure'

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        env:
          ARM_CLIENT_ID: 683ee45a-4174-4052-8bd1-ee07ddddb081
          ARM_SUBSCRIPTION_ID: cf59511e-1dbb-417d-ba5e-185454d163ee
          ARM_TENANT_ID: 0746364f-29a1-4bd8-8f34-fd815db4f514
        run: terraform apply -auto-approve
